---
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/core:prod', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/core:prod']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'core',
      '--image', 'gcr.io/$PROJECT_ID/core:prod',
      '--region', 'us-central1',
      '--platform', 'managed'
    ]
images:
  - gcr.io/$PROJECT_ID/core:prod
