name: deploy
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: go-setup
      uses: actions/setup-go@v1
      with:
        go-version: '1.14'
    - name: build
      run: make container
    - name: tag
      run: docker tag core:prod gcr.io/core-271417/core:prod
    - name: login
      run: echo INPUT_KEYDATA | base64 --decode | docker login -u _json_key --password-stdin https://gcr.io
      env:
        keydata: ${{ secrets.GCRDeployKey }}
    - name: push
      run: docker push gcr.io/core-271417/core:prod