name: deploy
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: go-setup
      uses: actions/setup-go@v1
      with:
        go-version: '1.14'
    - name: build
      run: make container
