---
name: test
on:
  - push
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: go-setup
        uses: actions/setup-go@v1
        with:
          go-version: '1.14'
      - name: mysql-shutdown
        run: sudo service mysql stop
      - name: mysql-setup
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'core-test'
          mysql user: 'devuser'
          mysql password: 'devpass'
      - name: build
        run: make all
      - name: wait
        run: sleep 60
      - name: migration
        run: make test-migration
      - name: unit-test
        run: make test
